//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarotor.LocalizationResources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpressLocalizationResource_tr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpressLocalizationResource_tr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Tarotor.LocalizationResources.ExpressLocalizationResource_tr", typeof(ExpressLocalizationResource_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ___0___and___1___do_not_match_ {
            get {
                return ResourceManager.GetString("\'{0}\' and \'{1}\' do not match.", resourceCulture);
            }
        }
        
        internal static string A_non_empty_request_body_is_required_ {
            get {
                return ResourceManager.GetString("A non-empty request body is required.", resourceCulture);
            }
        }
        
        internal static string A_user_with_this_login_already_exists_ {
            get {
                return ResourceManager.GetString("A user with this login already exists.", resourceCulture);
            }
        }
        
        internal static string A_value_for_the___0___parameter_or_property_was_not_provided_ {
            get {
                return ResourceManager.GetString("A value for the \'{0}\' parameter or property was not provided.", resourceCulture);
            }
        }
        
        internal static string A_value_is_required_ {
            get {
                return ResourceManager.GetString("A value is required.", resourceCulture);
            }
        }
        
        internal static string An_unknown_failure_has_occurred_ {
            get {
                return ResourceManager.GetString("An unknown failure has occurred.", resourceCulture);
            }
        }
        
        internal static string Both_ErrorMessageResourceType_and_ErrorMessageResourceName_need_to_be_set_on_this_attribute_ {
            get {
                return ResourceManager.GetString("Both ErrorMessageResourceType and ErrorMessageResourceName need to be set on this" +
                        " attribute.", resourceCulture);
            }
        }
        
        internal static string Cannot_retrieve_property___0___because_localization_failed___Type___1___is_not_public_or_does_not_contain_a_public_static_string_property_with_the_name___2___ {
            get {
                return ResourceManager.GetString("Cannot retrieve property \'{0}\' because localization failed.  Type \'{1}\' is not pu" +
                        "blic or does not contain a public static string property with the name \'{2}\'.", resourceCulture);
            }
        }
        
        internal static string Could_not_convert_the_value_of_type___0___to___1___as_expected_by_method__2___3__ {
            get {
                return ResourceManager.GetString("Could not convert the value of type \'{0}\' to \'{1}\' as expected by method {2}.{3}." +
                        "", resourceCulture);
            }
        }
        
        internal static string Could_not_find_a_property_named__0__ {
            get {
                return ResourceManager.GetString("Could not find a property named {0}.", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string Either_ErrorMessageString_or_ErrorMessageResourceName_must_be_set__but_not_both_ {
            get {
                return ResourceManager.GetString("Either ErrorMessageString or ErrorMessageResourceName must be set, but not both.", resourceCulture);
            }
        }
        
        internal static string Email___0___is_already_taken_ {
            get {
                return ResourceManager.GetString("Email \'{0}\' is already taken.", resourceCulture);
            }
        }
        
        internal static string Email___0___is_invalid_ {
            get {
                return ResourceManager.GetString("Email \'{0}\' is invalid.", resourceCulture);
            }
        }
        
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        internal static string Incorrect_password_ {
            get {
                return ResourceManager.GetString("Incorrect password.", resourceCulture);
            }
        }
        
        internal static string Invalid_token_ {
            get {
                return ResourceManager.GetString("Invalid token.", resourceCulture);
            }
        }
        
        internal static string IsValid_object_value__has_not_been_implemented_by_this_class___The_preferred_entry_point_is_GetValidationResult___and_classes_should_override_IsValid_object_value__ValidationContext_context__ {
            get {
                return ResourceManager.GetString("IsValid(object value) has not been implemented by this class.  The preferred entr" +
                        "y point is GetValidationResult() and classes should override IsValid(object valu" +
                        "e, ValidationContext context).", resourceCulture);
            }
        }
        
        internal static string Lockout_is_not_enabled_for_this_user_ {
            get {
                return ResourceManager.GetString("Lockout is not enabled for this user.", resourceCulture);
            }
        }
        
        internal static string MaxLengthAttribute_must_have_a_Length_value_that_is_greater_than_zero__Use_MaxLength___without_parameters_to_indicate_that_the_string_or_array_can_have_the_maximum_allowable_length_ {
            get {
                return ResourceManager.GetString("MaxLengthAttribute must have a Length value that is greater than zero. Use MaxLen" +
                        "gth() without parameters to indicate that the string or array can have the maxim" +
                        "um allowable length.", resourceCulture);
            }
        }
        
        internal static string MetadataClassType_cannot_be_null_ {
            get {
                return ResourceManager.GetString("MetadataClassType cannot be null.", resourceCulture);
            }
        }
        
        internal static string MinLengthAttribute_must_have_a_Length_value_that_is_zero_or_greater_ {
            get {
                return ResourceManager.GetString("MinLengthAttribute must have a Length value that is zero or greater.", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Optimistic_concurrency_failure__object_has_been_modified_ {
            get {
                return ResourceManager.GetString("Optimistic concurrency failure, object has been modified.", resourceCulture);
            }
        }
        
        internal static string Passwords_must_be_at_least__0__characters_ {
            get {
                return ResourceManager.GetString("Passwords must be at least {0} characters.", resourceCulture);
            }
        }
        
        internal static string Passwords_must_have_at_least_one_digit___0___9___ {
            get {
                return ResourceManager.GetString("Passwords must have at least one digit (\'0\'-\'9\').", resourceCulture);
            }
        }
        
        internal static string Passwords_must_have_at_least_one_lowercase___a___z___ {
            get {
                return ResourceManager.GetString("Passwords must have at least one lowercase (\'a\'-\'z\').", resourceCulture);
            }
        }
        
        internal static string Passwords_must_have_at_least_one_non_alphanumeric_character_ {
            get {
                return ResourceManager.GetString("Passwords must have at least one non alphanumeric character.", resourceCulture);
            }
        }
        
        internal static string Passwords_must_have_at_least_one_uppercase___A___Z___ {
            get {
                return ResourceManager.GetString("Passwords must have at least one uppercase (\'A\'-\'Z\').", resourceCulture);
            }
        }
        
        internal static string Passwords_must_use_at_least__0__different_characters_ {
            get {
                return ResourceManager.GetString("Passwords must use at least {0} different characters.", resourceCulture);
            }
        }
        
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        internal static string Recovery_code_redemption_failed_ {
            get {
                return ResourceManager.GetString("Recovery code redemption failed.", resourceCulture);
            }
        }
        
        internal static string Role_name___0___is_already_taken_ {
            get {
                return ResourceManager.GetString("Role name \'{0}\' is already taken.", resourceCulture);
            }
        }
        
        internal static string Role_name___0___is_invalid_ {
            get {
                return ResourceManager.GetString("Role name \'{0}\' is invalid.", resourceCulture);
            }
        }
        
        internal static string The_argument___0___cannot_be_null__empty_or_contain_only_whitespace_ {
            get {
                return ResourceManager.GetString("The argument \'{0}\' cannot be null, empty or contain only whitespace.", resourceCulture);
            }
        }
        
        internal static string The_associated_metadata_type_for_type___0___contains_the_following_unknown_properties_or_fields___1___Please_make_sure_that_the_names_of_these_members_match_the_names_of_the_properties_on_the_main_type_ {
            get {
                return ResourceManager.GetString("The associated metadata type for type \'{0}\' contains the following unknown proper" +
                        "ties or fields: {1}. Please make sure that the names of these members match the " +
                        "names of the properties on the main type.", resourceCulture);
            }
        }
        
        internal static string The_custom_DataType_string_cannot_be_null_or_empty_ {
            get {
                return ResourceManager.GetString("The custom DataType string cannot be null or empty.", resourceCulture);
            }
        }
        
        internal static string The_custom_validation_type___0___must_be_public_ {
            get {
                return ResourceManager.GetString("The custom validation type \'{0}\' must be public.", resourceCulture);
            }
        }
        
        internal static string The_CustomValidationAttribute_method___0___does_not_exist_in_type___1___or_is_not_public_and_static_ {
            get {
                return ResourceManager.GetString("The CustomValidationAttribute method \'{0}\' does not exist in type \'{1}\' or is not" +
                        " public and static.", resourceCulture);
            }
        }
        
        internal static string The_CustomValidationAttribute_method___0___in_type___1___must_match_the_expected_signature__public_static_ValidationResult__0__object_value__ValidationContext_context____The_value_can_be_strongly_typed___The_ValidationContext_parameter_is_optional_ {
            get {
                return ResourceManager.GetString("The CustomValidationAttribute method \'{0}\' in type \'{1}\' must match the expected " +
                        "signature: public static ValidationResult {0}(object value, ValidationContext co" +
                        "ntext).  The value can be strongly typed.  The ValidationContext parameter is op" +
                        "tional.", resourceCulture);
            }
        }
        
        internal static string The_CustomValidationAttribute_method___0___in_type___1___must_return_System_ComponentModel_DataAnnotations_ValidationResult___Use_System_ComponentModel_DataAnnotations_ValidationResult_Success_to_represent_success_ {
            get {
                return ResourceManager.GetString("The CustomValidationAttribute method \'{0}\' in type \'{1}\' must return System.Compo" +
                        "nentModel.DataAnnotations.ValidationResult.  Use System.ComponentModel.DataAnnot" +
                        "ations.ValidationResult.Success to represent success.", resourceCulture);
            }
        }
        
        internal static string The_CustomValidationAttribute_Method_was_not_specified_ {
            get {
                return ResourceManager.GetString("The CustomValidationAttribute.Method was not specified.", resourceCulture);
            }
        }
        
        internal static string The_CustomValidationAttribute_ValidatorType_was_not_specified_ {
            get {
                return ResourceManager.GetString("The CustomValidationAttribute.ValidatorType was not specified.", resourceCulture);
            }
        }
        
        internal static string The_field_must_be_a_number_ {
            get {
                return ResourceManager.GetString("The field must be a number.", resourceCulture);
            }
        }
        
        internal static string The_field_of_type__0__must_be_a_string__array_or_ICollection_type_ {
            get {
                return ResourceManager.GetString("The field of type {0} must be a string, array or ICollection type.", resourceCulture);
            }
        }
        
        internal static string The_field__0__is_invalid_ {
            get {
                return ResourceManager.GetString("The field {0} is invalid.", resourceCulture);
            }
        }
        
        internal static string The_field__0__must_be_a_number_ {
            get {
                return ResourceManager.GetString("The field {0} must be a number.", resourceCulture);
            }
        }
        
        internal static string The_field__0__must_be_a_string_or_array_type_with_a_maximum_length_of___1___ {
            get {
                return ResourceManager.GetString("The field {0} must be a string or array type with a maximum length of \'{1}\'.", resourceCulture);
            }
        }
        
        internal static string The_field__0__must_be_a_string_or_array_type_with_a_minimum_length_of___1___ {
            get {
                return ResourceManager.GetString("The field {0} must be a string or array type with a minimum length of \'{1}\'.", resourceCulture);
            }
        }
        
        internal static string The_field__0__must_be_a_string_with_a_maximum_length_of__1__ {
            get {
                return ResourceManager.GetString("The field {0} must be a string with a maximum length of {1}.", resourceCulture);
            }
        }
        
        internal static string The_field__0__must_be_a_string_with_a_minimum_length_of__2__and_a_maximum_length_of__1__ {
            get {
                return ResourceManager.GetString("The field {0} must be a string with a minimum length of {2} and a maximum length " +
                        "of {1}.", resourceCulture);
            }
        }
        
        internal static string The_field__0__must_be_between__1__and__2__ {
            get {
                return ResourceManager.GetString("The field {0} must be between {1} and {2}.", resourceCulture);
            }
        }
        
        internal static string The_field__0__must_match_the_regular_expression___1___ {
            get {
                return ResourceManager.GetString("The field {0} must match the regular expression \'{1}\'.", resourceCulture);
            }
        }
        
        internal static string The_instance_provided_must_match_the_ObjectInstance_on_the_ValidationContext_supplied_ {
            get {
                return ResourceManager.GetString("The instance provided must match the ObjectInstance on the ValidationContext supp" +
                        "lied.", resourceCulture);
            }
        }
        
        internal static string The_key_parameter_at_position__0__is_null__Every_key_control_parameter_must_be_a_string_ {
            get {
                return ResourceManager.GetString("The key parameter at position {0} is null. Every key control parameter must be a " +
                        "string.", resourceCulture);
            }
        }
        
        internal static string The_key_parameter_at_position__0__with_value___1___is_not_a_string__Every_key_control_parameter_must_be_a_string_ {
            get {
                return ResourceManager.GetString("The key parameter at position {0} with value \'{1}\' is not a string. Every key con" +
                        "trol parameter must be a string.", resourceCulture);
            }
        }
        
        internal static string The_key_parameter_at_position__0__with_value___1___occurs_more_than_once_ {
            get {
                return ResourceManager.GetString("The key parameter at position {0} with value \'{1}\' occurs more than once.", resourceCulture);
            }
        }
        
        internal static string The_maximum_length_must_be_a_nonnegative_integer_ {
            get {
                return ResourceManager.GetString("The maximum length must be a nonnegative integer.", resourceCulture);
            }
        }
        
        internal static string The_maximum_value___0___must_be_greater_than_or_equal_to_the_minimum_value___1___ {
            get {
                return ResourceManager.GetString("The maximum value \'{0}\' must be greater than or equal to the minimum value \'{1}\'." +
                        "", resourceCulture);
            }
        }
        
        internal static string The_minimum_and_maximum_values_must_be_set_ {
            get {
                return ResourceManager.GetString("The minimum and maximum values must be set.", resourceCulture);
            }
        }
        
        internal static string The_number_of_control_parameters_must_be_even_ {
            get {
                return ResourceManager.GetString("The number of control parameters must be even.", resourceCulture);
            }
        }
        
        internal static string The_OperandType_must_be_set_when_strings_are_used_for_minimum_and_maximum_values_ {
            get {
                return ResourceManager.GetString("The OperandType must be set when strings are used for minimum and maximum values." +
                        "", resourceCulture);
            }
        }
        
        internal static string The_pattern_must_be_set_to_a_valid_regular_expression_ {
            get {
                return ResourceManager.GetString("The pattern must be set to a valid regular expression.", resourceCulture);
            }
        }
        
        internal static string The_property___0___on_resource_type___1___is_not_a_string_type_ {
            get {
                return ResourceManager.GetString("The property \'{0}\' on resource type \'{1}\' is not a string type.", resourceCulture);
            }
        }
        
        internal static string The_property__0___1__could_not_be_found_ {
            get {
                return ResourceManager.GetString("The property {0}.{1} could not be found.", resourceCulture);
            }
        }
        
        internal static string The_resource_type___0___does_not_have_an_accessible_static_property_named___1___ {
            get {
                return ResourceManager.GetString("The resource type \'{0}\' does not have an accessible static property named \'{1}\'.", resourceCulture);
            }
        }
        
        internal static string The_supplied_value_is_invalid_for__0__ {
            get {
                return ResourceManager.GetString("The supplied value is invalid for {0}.", resourceCulture);
            }
        }
        
        internal static string The_supplied_value_is_invalid_ {
            get {
                return ResourceManager.GetString("The supplied value is invalid.", resourceCulture);
            }
        }
        
        internal static string The_type___0___does_not_contain_a_public_property_named___1___ {
            get {
                return ResourceManager.GetString("The type \'{0}\' does not contain a public property named \'{1}\'.", resourceCulture);
            }
        }
        
        internal static string The_type___0___needs_to_represent_an_enumeration_type_ {
            get {
                return ResourceManager.GetString("The type \'{0}\' needs to represent an enumeration type.", resourceCulture);
            }
        }
        
        internal static string The_type_provided_for_EnumDataTypeAttribute_cannot_be_null_ {
            get {
                return ResourceManager.GetString("The type provided for EnumDataTypeAttribute cannot be null.", resourceCulture);
            }
        }
        
        internal static string The_type__0__must_implement__1__ {
            get {
                return ResourceManager.GetString("The type {0} must implement {1}.", resourceCulture);
            }
        }
        
        internal static string The_value___0___is_invalid_ {
            get {
                return ResourceManager.GetString("The value \'{0}\' is invalid.", resourceCulture);
            }
        }
        
        internal static string The_value___0___is_not_valid_for__1__ {
            get {
                return ResourceManager.GetString("The value \'{0}\' is not valid for {1}.", resourceCulture);
            }
        }
        
        internal static string The_value___0___is_not_valid_ {
            get {
                return ResourceManager.GetString("The value \'{0}\' is not valid.", resourceCulture);
            }
        }
        
        internal static string The_value_for_property___0___must_be_of_type___1___ {
            get {
                return ResourceManager.GetString("The value for property \'{0}\' must be of type \'{1}\'.", resourceCulture);
            }
        }
        
        internal static string The__0__field_is_not_a_valid_credit_card_number_ {
            get {
                return ResourceManager.GetString("The {0} field is not a valid credit card number.", resourceCulture);
            }
        }
        
        internal static string The__0__field_is_not_a_valid_e_mail_address_ {
            get {
                return ResourceManager.GetString("The {0} field is not a valid e-mail address.", resourceCulture);
            }
        }
        
        internal static string The__0__field_is_not_a_valid_fully_qualified_http__https__or_ftp_URL_ {
            get {
                return ResourceManager.GetString("The {0} field is not a valid fully-qualified http, https, or ftp URL.", resourceCulture);
            }
        }
        
        internal static string The__0__field_is_not_a_valid_phone_number_ {
            get {
                return ResourceManager.GetString("The {0} field is not a valid phone number.", resourceCulture);
            }
        }
        
        internal static string The__0__field_is_required_ {
            get {
                return ResourceManager.GetString("The {0} field is required.", resourceCulture);
            }
        }
        
        internal static string The__0__field_only_accepts_files_with_the_following_extensions___1_ {
            get {
                return ResourceManager.GetString("The {0} field only accepts files with the following extensions: {1}", resourceCulture);
            }
        }
        
        internal static string The__0__property_has_not_been_set___Use_the__1__method_to_get_the_value_ {
            get {
                return ResourceManager.GetString("The {0} property has not been set.  Use the {1} method to get the value.", resourceCulture);
            }
        }
        
        internal static string User_already_has_a_password_set_ {
            get {
                return ResourceManager.GetString("User already has a password set.", resourceCulture);
            }
        }
        
        internal static string User_already_in_role___0___ {
            get {
                return ResourceManager.GetString("User already in role \'{0}\'.", resourceCulture);
            }
        }
        
        internal static string User_is_not_in_role___0___ {
            get {
                return ResourceManager.GetString("User is not in role \'{0}\'.", resourceCulture);
            }
        }
        
        internal static string User_name___0___is_already_taken_ {
            get {
                return ResourceManager.GetString("User name \'{0}\' is already taken.", resourceCulture);
            }
        }
        
        internal static string User_name___0___is_invalid__can_only_contain_letters_or_digits_ {
            get {
                return ResourceManager.GetString("User name \'{0}\' is invalid, can only contain letters or digits.", resourceCulture);
            }
        }
        
        internal static string _0__is_not_valid_ {
            get {
                return ResourceManager.GetString("{0} is not valid.", resourceCulture);
            }
        }
        
        internal static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm password", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Current_password {
            get {
                return ResourceManager.GetString("Current password", resourceCulture);
            }
        }
        
        internal static string New_password {
            get {
                return ResourceManager.GetString("New password", resourceCulture);
            }
        }
        
        internal static string Phone_number {
            get {
                return ResourceManager.GetString("Phone number", resourceCulture);
            }
        }
        
        internal static string User_name {
            get {
                return ResourceManager.GetString("User name", resourceCulture);
            }
        }
        
        internal static string Verification_code {
            get {
                return ResourceManager.GetString("Verification code", resourceCulture);
            }
        }
        
        internal static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        internal static string Remember_this_machine_ {
            get {
                return ResourceManager.GetString("Remember this machine?", resourceCulture);
            }
        }
        
        internal static string Daily_Limit {
            get {
                return ResourceManager.GetString("Daily Limit", resourceCulture);
            }
        }
        
        internal static string Question_Limit {
            get {
                return ResourceManager.GetString("Question Limit", resourceCulture);
            }
        }
        
        internal static string Tarot_Price {
            get {
                return ResourceManager.GetString("Tarot Price", resourceCulture);
            }
        }
        
        internal static string Question_Price {
            get {
                return ResourceManager.GetString("Question Price", resourceCulture);
            }
        }
        
        internal static string Selection_Card_Count {
            get {
                return ResourceManager.GetString("Selection Card Count", resourceCulture);
            }
        }
        
        internal static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        internal static string Birth_Date {
            get {
                return ResourceManager.GetString("Birth Date", resourceCulture);
            }
        }
        
        internal static string Your_Photo {
            get {
                return ResourceManager.GetString("Your Photo", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string Choose_file {
            get {
                return ResourceManager.GetString("Choose file", resourceCulture);
            }
        }
    }
}
