//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarotor.LocalizationResources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewLocalizationResource_tr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewLocalizationResource_tr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Tarotor.LocalizationResources.ViewLocalizationResource_tr", typeof(ViewLocalizationResource_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string _p_Your_account_contains_personal_data_that_you_have_given_us__This_page_allows_you_to_download_or_delete_that_data___p__p__strong_Deleting_this_data_will_permanently_remove_your_account__and_this_cannot_be_recovered___strong___p_ {
            get {
                return ResourceManager.GetString("<p>Your account contains personal data that you have given us. This page allows y" +
                        "ou to download or delete that data.</p><p><strong>Deleting this data will perman" +
                        "ently remove your account, and this cannot be recovered.</strong></p>", resourceCulture);
            }
        }
        
        internal static string Access_denied {
            get {
                return ResourceManager.GetString("Access denied", resourceCulture);
            }
        }
        
        internal static string Add_another_service_to_log_in_ {
            get {
                return ResourceManager.GetString("Add another service to log in.", resourceCulture);
            }
        }
        
        internal static string Add_authenticator_app {
            get {
                return ResourceManager.GetString("Add authenticator app", resourceCulture);
            }
        }
        
        internal static string An_error_occurred_while_processing_your_request_ {
            get {
                return ResourceManager.GetString("An error occurred while processing your request.", resourceCulture);
            }
        }
        
        internal static string Associate_your__0__account_ {
            get {
                return ResourceManager.GetString("Associate your {0} account.", resourceCulture);
            }
        }
        
        internal static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        internal static string Change_your_account_settings {
            get {
                return ResourceManager.GetString("Change your account settings", resourceCulture);
            }
        }
        
        internal static string Configure_authenticator_app {
            get {
                return ResourceManager.GetString("Configure authenticator app", resourceCulture);
            }
        }
        
        internal static string Confirm_email {
            get {
                return ResourceManager.GetString("Confirm email", resourceCulture);
            }
        }
        
        internal static string Confirm_your_email {
            get {
                return ResourceManager.GetString("Confirm your email", resourceCulture);
            }
        }
        
        internal static string Create_a_new_account_ {
            get {
                return ResourceManager.GetString("Create a new account.", resourceCulture);
            }
        }
        
        internal static string Development_Mode {
            get {
                return ResourceManager.GetString("Development Mode", resourceCulture);
            }
        }
        
        internal static string Disable_2FA {
            get {
                return ResourceManager.GetString("Disable 2FA", resourceCulture);
            }
        }
        
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        internal static string Download_Your_Data {
            get {
                return ResourceManager.GetString("Download Your Data", resourceCulture);
            }
        }
        
        internal static string Enter_your_email_ {
            get {
                return ResourceManager.GetString("Enter your email.", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Error_from_external_provider___0_ {
            get {
                return ResourceManager.GetString("Error from external provider: {0}", resourceCulture);
            }
        }
        
        internal static string Error_loading_external_login_information_during_confirmation_ {
            get {
                return ResourceManager.GetString("Error loading external login information during confirmation.", resourceCulture);
            }
        }
        
        internal static string Error_loading_external_login_information_ {
            get {
                return ResourceManager.GetString("Error loading external login information.", resourceCulture);
            }
        }
        
        internal static string External_logins {
            get {
                return ResourceManager.GetString("External logins", resourceCulture);
            }
        }
        
        internal static string Forget_this_browser {
            get {
                return ResourceManager.GetString("Forget this browser", resourceCulture);
            }
        }
        
        internal static string Forgot_password_confirmation {
            get {
                return ResourceManager.GetString("Forgot password confirmation", resourceCulture);
            }
        }
        
        internal static string Forgot_your_password_ {
            get {
                return ResourceManager.GetString("Forgot your password?", resourceCulture);
            }
        }
        
        internal static string Generate_Recovery_Codes {
            get {
                return ResourceManager.GetString("Generate Recovery Codes", resourceCulture);
            }
        }
        
        internal static string Generate_two_factor_authentication__2FA__recovery_codes {
            get {
                return ResourceManager.GetString("Generate two-factor authentication (2FA) recovery codes", resourceCulture);
            }
        }
        
        internal static string Hello__0__ {
            get {
                return ResourceManager.GetString("Hello {0}!", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Invalid_authenticator_code_ {
            get {
                return ResourceManager.GetString("Invalid authenticator code.", resourceCulture);
            }
        }
        
        internal static string Invalid_login_attempt_ {
            get {
                return ResourceManager.GetString("Invalid login attempt.", resourceCulture);
            }
        }
        
        internal static string Invalid_recovery_code_entered_ {
            get {
                return ResourceManager.GetString("Invalid recovery code entered.", resourceCulture);
            }
        }
        
        internal static string Locked_out {
            get {
                return ResourceManager.GetString("Locked out", resourceCulture);
            }
        }
        
        internal static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        internal static string Log_in_using_your_external_account {
            get {
                return ResourceManager.GetString("Log in using your external account", resourceCulture);
            }
        }
        
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        internal static string Manage_your_account {
            get {
                return ResourceManager.GetString("Manage your account", resourceCulture);
            }
        }
        
        internal static string Manage_your_external_logins {
            get {
                return ResourceManager.GetString("Manage your external logins", resourceCulture);
            }
        }
        
        internal static string Once_you_have_scanned_the_QR_code_or_input_the_key_above__your_two_factor_authentication_app_will_provide_you_with_a_unique_code__Enter_the_code_in_the_confirmation_box_below_ {
            get {
                return ResourceManager.GetString("Once you have scanned the QR code or input the key above, your two factor authent" +
                        "ication app will provide you with a unique code. Enter the code in the confirmat" +
                        "ion box below.", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Password_not_correct_ {
            get {
                return ResourceManager.GetString("Password not correct.", resourceCulture);
            }
        }
        
        internal static string Personal_Data {
            get {
                return ResourceManager.GetString("Personal Data", resourceCulture);
            }
        }
        
        internal static string Please_check_your_email_to_reset_your_password_ {
            get {
                return ResourceManager.GetString("Please check your email to reset your password.", resourceCulture);
            }
        }
        
        internal static string Please_enter_a_valid_number_ {
            get {
                return ResourceManager.GetString("Please enter a valid number.", resourceCulture);
            }
        }
        
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        internal static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy Policy", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string Recovery_code_verification {
            get {
                return ResourceManager.GetString("Recovery code verification", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string Register_as_a_new_user {
            get {
                return ResourceManager.GetString("Register as a new user", resourceCulture);
            }
        }
        
        internal static string Registered_Logins {
            get {
                return ResourceManager.GetString("Registered Logins", resourceCulture);
            }
        }
        
        internal static string Remember_me_ {
            get {
                return ResourceManager.GetString("Remember me?", resourceCulture);
            }
        }
        
        internal static string Remove_this_login_from_your_account {
            get {
                return ResourceManager.GetString("Remove this login from your account", resourceCulture);
            }
        }
        
        internal static string Remove__0_ {
            get {
                return ResourceManager.GetString("Remove {0}", resourceCulture);
            }
        }
        
        internal static string Request_ID_ {
            get {
                return ResourceManager.GetString("Request ID:", resourceCulture);
            }
        }
        
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        internal static string Reset_authenticator_app {
            get {
                return ResourceManager.GetString("Reset authenticator app", resourceCulture);
            }
        }
        
        internal static string Reset_authenticator_key {
            get {
                return ResourceManager.GetString("Reset authenticator key", resourceCulture);
            }
        }
        
        internal static string Reset_password {
            get {
                return ResourceManager.GetString("Reset password", resourceCulture);
            }
        }
        
        internal static string Reset_password_confirmation {
            get {
                return ResourceManager.GetString("Reset password confirmation", resourceCulture);
            }
        }
        
        internal static string Reset_recovery_codes {
            get {
                return ResourceManager.GetString("Reset recovery codes", resourceCulture);
            }
        }
        
        internal static string Reset_your_password_ {
            get {
                return ResourceManager.GetString("Reset your password.", resourceCulture);
            }
        }
        
        internal static string Sample_Form {
            get {
                return ResourceManager.GetString("Sample Form", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Send_verification_email {
            get {
                return ResourceManager.GetString("Send verification email", resourceCulture);
            }
        }
        
        internal static string Set_password {
            get {
                return ResourceManager.GetString("Set password", resourceCulture);
            }
        }
        
        internal static string Setup_authenticator_app {
            get {
                return ResourceManager.GetString("Setup authenticator app", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string Thank_you_for_confirming_your_email_ {
            get {
                return ResourceManager.GetString("Thank you for confirming your email.", resourceCulture);
            }
        }
        
        internal static string The_current_browser_has_been_forgotten__When_you_login_again_from_this_browser_you_will_be_prompted_for_your_2fa_code_ {
            get {
                return ResourceManager.GetString("The current browser has been forgotten. When you login again from this browser yo" +
                        "u will be prompted for your 2fa code.", resourceCulture);
            }
        }
        
        internal static string The_external_login_was_added_ {
            get {
                return ResourceManager.GetString("The external login was added.", resourceCulture);
            }
        }
        
        internal static string The_external_login_was_removed_ {
            get {
                return ResourceManager.GetString("The external login was removed.", resourceCulture);
            }
        }
        
        internal static string This_account_has_been_locked_out__please_try_again_later_ {
            get {
                return ResourceManager.GetString("This account has been locked out, please try again later.", resourceCulture);
            }
        }
        
        internal static string To_use_an_authenticator_app_go_through_the_following_steps_ {
            get {
                return ResourceManager.GetString("To use an authenticator app go through the following steps:", resourceCulture);
            }
        }
        
        internal static string Two_factor_authentication {
            get {
                return ResourceManager.GetString("Two-factor authentication", resourceCulture);
            }
        }
        
        internal static string Two_factor_authentication__2FA_ {
            get {
                return ResourceManager.GetString("Two-factor authentication (2FA)", resourceCulture);
            }
        }
        
        internal static string Update_password {
            get {
                return ResourceManager.GetString("Update password", resourceCulture);
            }
        }
        
        internal static string Use_a_local_account_to_log_in_ {
            get {
                return ResourceManager.GetString("Use a local account to log in.", resourceCulture);
            }
        }
        
        internal static string Use_another_service_to_log_in_ {
            get {
                return ResourceManager.GetString("Use another service to log in.", resourceCulture);
            }
        }
        
        internal static string Use_this_page_to_detail_your_site_s_privacy_policy_ {
            get {
                return ResourceManager.GetString("Use this page to detail your site\'s privacy policy.", resourceCulture);
            }
        }
        
        internal static string Verification_Code {
            get {
                return ResourceManager.GetString("Verification Code", resourceCulture);
            }
        }
        
        internal static string Verification_email_sent__Please_check_your_email_ {
            get {
                return ResourceManager.GetString("Verification email sent. Please check your email.", resourceCulture);
            }
        }
        
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string You_do_not_have_a_local_username_password_for_this_site__Add_a_local_account_so_you_can_log_in_without_an_external_login_ {
            get {
                return ResourceManager.GetString("You do not have a local username/password for this site. Add a local account so y" +
                        "ou can log in without an external login.", resourceCulture);
            }
        }
        
        internal static string You_do_not_have_access_to_this_resource_ {
            get {
                return ResourceManager.GetString("You do not have access to this resource.", resourceCulture);
            }
        }
        
        internal static string You_have_generated_new_recovery_codes_ {
            get {
                return ResourceManager.GetString("You have generated new recovery codes.", resourceCulture);
            }
        }
        
        internal static string You_have_requested_to_log_in_with_a_recovery_code__This_login_will_not_be_remembered_until_you_provide_an_authenticator_app_code_at_log_in_or_disable_2FA_and_log_in_again_ {
            get {
                return ResourceManager.GetString("You have requested to log in with a recovery code. This login will not be remembe" +
                        "red until you provide an authenticator app code at log in or disable 2FA and log" +
                        " in again.", resourceCulture);
            }
        }
        
        internal static string You_have_successfully_logged_out_of_the_application_ {
            get {
                return ResourceManager.GetString("You have successfully logged out of the application.", resourceCulture);
            }
        }
        
        internal static string You_ve_successfully_authenticated_with__strong__0___strong___Please_enter_an_email_address_for_this_site_below_and_click_the_Register_button_to_finish_logging_in_ {
            get {
                return ResourceManager.GetString("You\'ve successfully authenticated with <strong>{0}</strong>. Please enter an emai" +
                        "l address for this site below and click the Register button to finish logging in" +
                        ".", resourceCulture);
            }
        }
        
        internal static string Your_authenticator_app_has_been_verified_ {
            get {
                return ResourceManager.GetString("Your authenticator app has been verified.", resourceCulture);
            }
        }
        
        internal static string Your_authenticator_app_key_has_been_reset__you_will_need_to_configure_your_authenticator_app_using_the_new_key_ {
            get {
                return ResourceManager.GetString("Your authenticator app key has been reset, you will need to configure your authen" +
                        "ticator app using the new key.", resourceCulture);
            }
        }
        
        internal static string Your_login_is_protected_with_an_authenticator_app__Enter_your_authenticator_code_below_ {
            get {
                return ResourceManager.GetString("Your login is protected with an authenticator app. Enter your authenticator code " +
                        "below.", resourceCulture);
            }
        }
        
        internal static string Your_password_has_been_changed_ {
            get {
                return ResourceManager.GetString("Your password has been changed.", resourceCulture);
            }
        }
        
        internal static string Your_password_has_been_set_ {
            get {
                return ResourceManager.GetString("Your password has been set.", resourceCulture);
            }
        }
        
        internal static string Your_profile_has_been_updated {
            get {
                return ResourceManager.GetString("Your profile has been updated", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        internal static string How_ {
            get {
                return ResourceManager.GetString("How?", resourceCulture);
            }
        }
        
        internal static string Read_More_Messages {
            get {
                return ResourceManager.GetString("Read More Messages", resourceCulture);
            }
        }
        
        internal static string Message_Center {
            get {
                return ResourceManager.GetString("Message Center", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Registration_Form {
            get {
                return ResourceManager.GetString("Registration Form", resourceCulture);
            }
        }
        
        internal static string You_don_t_have_to_write_your_details_every_time_if_you_register__It_s_easy_ {
            get {
                return ResourceManager.GetString("You don\'t have to write your details every time if you register. It\'s easy.", resourceCulture);
            }
        }
        
        internal static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Birth_Date {
            get {
                return ResourceManager.GetString("Birth Date", resourceCulture);
            }
        }
    }
}
